// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protobuf/account.proto

package grpc

/*
	Params
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/golang/protobuf/ptypes/struct"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import github_com_gallactic_gallactic_core_validator "github.com/gallactic/gallactic/core/validator"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_bc1beb58f8e659c9, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ValidatorOutput struct {
	BlockHeight          uint64                                                     `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	BondedValidators     []*github_com_gallactic_gallactic_core_validator.Validator `protobuf:"bytes,2,rep,name=BondedValidators,customtype=github.com/gallactic/gallactic/core/validator.Validator" json:"BondedValidators"`
	UnbondingValidators  []*github_com_gallactic_gallactic_core_validator.Validator `protobuf:"bytes,3,rep,name=UnbondingValidators,customtype=github.com/gallactic/gallactic/core/validator.Validator" json:"UnbondingValidators"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *ValidatorOutput) Reset()         { *m = ValidatorOutput{} }
func (m *ValidatorOutput) String() string { return proto.CompactTextString(m) }
func (*ValidatorOutput) ProtoMessage()    {}
func (*ValidatorOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_bc1beb58f8e659c9, []int{1}
}
func (m *ValidatorOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorOutput.Unmarshal(m, b)
}
func (m *ValidatorOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorOutput.Marshal(b, m, deterministic)
}
func (dst *ValidatorOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorOutput.Merge(dst, src)
}
func (m *ValidatorOutput) XXX_Size() int {
	return xxx_messageInfo_ValidatorOutput.Size(m)
}
func (m *ValidatorOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorOutput proto.InternalMessageInfo

func (m *ValidatorOutput) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "grpc.Empty")
	proto.RegisterType((*ValidatorOutput)(nil), "grpc.ValidatorOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	GetValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorOutput, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) GetValidators(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ValidatorOutput, error) {
	out := new(ValidatorOutput)
	err := c.cc.Invoke(ctx, "/grpc.Accounts/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	GetValidators(context.Context, *Empty) (*ValidatorOutput, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Accounts/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetValidators(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValidators",
			Handler:    _Accounts_GetValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/account.proto",
}

func init() { proto.RegisterFile("protobuf/account.proto", fileDescriptor_account_bc1beb58f8e659c9) }

var fileDescriptor_account_bc1beb58f8e659c9 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x37, 0x6d, 0xdf, 0x3f, 0x6c, 0x79, 0x79, 0x25, 0xa2, 0x94, 0x50, 0xd2, 0xd2, 0x53,
	0x2f, 0x6e, 0xa0, 0x3d, 0x78, 0x2c, 0x06, 0x44, 0x0f, 0x82, 0x50, 0xb0, 0xf7, 0xcd, 0x26, 0x6e,
	0x17, 0xd3, 0x9d, 0x90, 0xcc, 0x0a, 0x7e, 0x02, 0x4f, 0xde, 0x3d, 0xfa, 0x51, 0x3c, 0xf6, 0x22,
	0x78, 0xf6, 0x50, 0xa4, 0xf9, 0x22, 0xd2, 0xc4, 0x86, 0x50, 0xbd, 0x7a, 0x9b, 0x67, 0x76, 0x67,
	0x7e, 0xcf, 0xcc, 0xd0, 0xc3, 0x24, 0x05, 0x84, 0xc0, 0x5c, 0x7b, 0x5c, 0x08, 0x30, 0x1a, 0x59,
	0x91, 0xb0, 0x5b, 0x32, 0x4d, 0x84, 0x73, 0x24, 0x15, 0xce, 0x4d, 0xc0, 0x04, 0x2c, 0x3c, 0x09,
	0x12, 0xbc, 0xea, 0xf7, 0x46, 0x15, 0xa2, 0x88, 0xca, 0x22, 0xa7, 0x2b, 0x01, 0x64, 0x1c, 0x79,
	0x3c, 0x51, 0x1e, 0xd7, 0x1a, 0x90, 0xa3, 0x02, 0x9d, 0xed, 0xbc, 0x56, 0x3d, 0x32, 0x4c, 0x8d,
	0xf8, 0x04, 0x0e, 0xfe, 0xd0, 0x5f, 0xa7, 0x8b, 0x04, 0xef, 0x06, 0x2f, 0x0d, 0xfa, 0x7f, 0xc6,
	0x63, 0x15, 0x72, 0x84, 0xf4, 0xd2, 0x60, 0x62, 0xd0, 0xee, 0xd3, 0xb6, 0x1f, 0x83, 0xb8, 0x39,
	0x8f, 0x94, 0x9c, 0x63, 0xc7, 0xea, 0x5b, 0xc3, 0xd6, 0xb4, 0x9e, 0xb2, 0xef, 0x2d, 0xba, 0xe7,
	0x83, 0x0e, 0xa3, 0xb0, 0xaa, 0xcd, 0x3a, 0x8d, 0x7e, 0x73, 0xd8, 0x1e, 0x39, 0xac, 0x04, 0xb3,
	0x2d, 0x98, 0x5d, 0xa8, 0x0c, 0x67, 0x3c, 0x36, 0x91, 0x3f, 0x59, 0xae, 0x7a, 0xe4, 0x6d, 0xd5,
	0x3b, 0xae, 0x0f, 0xca, 0xe3, 0x98, 0x0b, 0x54, 0xa2, 0x16, 0x09, 0x48, 0x23, 0xef, 0x76, 0xdb,
	0x99, 0x55, 0x8c, 0xe9, 0x17, 0xa8, 0xfd, 0x60, 0xd1, 0xfd, 0x2b, 0x1d, 0x80, 0x0e, 0x95, 0x96,
	0x35, 0x33, 0xcd, 0x9f, 0x37, 0xf3, 0x1d, 0x77, 0x34, 0xa1, 0x7f, 0x4f, 0xca, 0xd3, 0x66, 0xf6,
	0x98, 0xfe, 0x3b, 0x8b, 0xb0, 0x66, 0xb6, 0xcd, 0x36, 0x77, 0x66, 0xc5, 0xe6, 0x9d, 0x83, 0x52,
	0xec, 0x2c, 0xdf, 0xef, 0x2e, 0xd7, 0x2e, 0x79, 0x5d, 0xbb, 0xe4, 0x7d, 0xed, 0x92, 0xc7, 0xdc,
	0x25, 0x4f, 0xb9, 0x4b, 0x9e, 0x73, 0x97, 0x2c, 0x73, 0x97, 0x04, 0xbf, 0x8b, 0x41, 0xc6, 0x1f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xc8, 0x19, 0xf1, 0x49, 0x02, 0x00, 0x00,
}
